#include "tim.h"

//------------------------------------------------------------------------------------------------- Channel-Map

const GPIO_Map_t TIM_CHx_MAP[] = {
  [TIM1_CH1_PA8] = { .port = GPIOA, .pin = 8, .alternate = 2 },
  [TIM1_CH1_PC8] = { .port = GPIOC, .pin = 8, .alternate = 2 },
  [TIM1_CH1N_PA7] = { .port = GPIOA, .pin = 7, .alternate = 2 },
  [TIM1_CH1N_PB13] = { .port = GPIOB, .pin = 13, .alternate = 2 },
  [TIM1_CH1N_PD2] = { .port = GPIOD, .pin = 2, .alternate = 2 },
  [TIM1_CH2_PA9] = { .port = GPIOA, .pin = 9, .alternate = 2 },
  [TIM1_CH2_PB3] = { .port = GPIOB, .pin = 3, .alternate = 1 },
  [TIM1_CH2_PC9] = { .port = GPIOC, .pin = 9, .alternate = 2 },
  [TIM1_CH2N_PB0] = { .port = GPIOB, .pin = 0, .alternate = 2 },
  [TIM1_CH2N_PB14] = { .port = GPIOB, .pin = 14, .alternate = 2 },
  [TIM1_CH2N_PD3] = { .port = GPIOD, .pin = 3, .alternate = 2 },
  [TIM1_CH3_PA10] = { .port = GPIOA, .pin = 10, .alternate = 2 },
  [TIM1_CH3_PB6] = { .port = GPIOB, .pin = 6, .alternate = 1 },
  [TIM1_CH3_PC10] = { .port = GPIOC, .pin = 10, .alternate = 2 },
  [TIM1_CH3N_PB1] = { .port = GPIOB, .pin = 1, .alternate = 2 },
  [TIM1_CH3N_PB15] = { .port = GPIOB, .pin = 15, .alternate = 2 },
  [TIM1_CH3N_PD4] = { .port = GPIOD, .pin = 4, .alternate = 2 },
  [TIM1_CH4_PA11] = { .port = GPIOA, .pin = 11, .alternate = 2 },
  [TIM1_CH4_PC11] = { .port = GPIOC, .pin = 11, .alternate = 2 },
  [TIM2_CH1_PA0] = { .port = GPIOA, .pin = 0, .alternate = 2 },
  [TIM2_CH2_PA1] = { .port = GPIOA, .pin = 1, .alternate = 2 },
  [TIM2_CH3_PA2] = { .port = GPIOA, .pin = 2, .alternate = 2 },
  [TIM2_CH4_PA3] = { .port = GPIOA, .pin = 3, .alternate = 2 },
  [TIM2_CH1_PA5] = { .port = GPIOA, .pin = 5, .alternate = 2 },
  [TIM2_CH1_PA15] = { .port = GPIOA, .pin = 15, .alternate = 2 },
  [TIM2_CH2_PB3] = { .port = GPIOB, .pin = 3, .alternate = 2 },
  [TIM2_CH3_PB10] = { .port = GPIOB, .pin = 10, .alternate = 2 },
  [TIM2_CH4_PB11] = { .port = GPIOB, .pin = 11, .alternate = 2 },
  [TIM2_CH1_PC4] = { .port = GPIOC, .pin = 4, .alternate = 2 },
  [TIM2_CH2_PC5] = { .port = GPIOC, .pin = 5, .alternate = 2 },
  [TIM2_CH3_PC6] = { .port = GPIOC, .pin = 6, .alternate = 2 },
  [TIM2_CH4_PC7] = { .port = GPIOC, .pin = 7, .alternate = 2 },
  [TIM3_CH1_PA6] = { .port = GPIOA, .pin = 6, .alternate = 1 },
  [TIM3_CH2_PA7] = { .port = GPIOA, .pin = 7, .alternate = 1 },
  [TIM3_CH3_PB0] = { .port = GPIOB, .pin = 0, .alternate = 1 },
  [TIM3_CH4_PB1] = { .port = GPIOB, .pin = 1, .alternate = 1 },
  [TIM3_CH1_PB4] = { .port = GPIOB, .pin = 4, .alternate = 1 },
  [TIM3_CH2_PB5] = { .port = GPIOB, .pin = 5, .alternate = 1 },
  [TIM3_CH1_PC6] = { .port = GPIOC, .pin = 6, .alternate = 1 },
  [TIM3_CH2_PC7] = { .port = GPIOC, .pin = 7, .alternate = 1 },
  [TIM3_CH3_PC8] = { .port = GPIOC, .pin = 8, .alternate = 1 },
  [TIM3_CH4_PC9] = { .port = GPIOC, .pin = 9, .alternate = 1 },
  [TIM15_CH1N_PA1] = { .port = GPIOA, .pin = 1, .alternate = 5 },
  [TIM15_CH1_PA2] = { .port = GPIOA, .pin = 2, .alternate = 5 },
  [TIM15_CH2_PA3] = { .port = GPIOA, .pin = 3, .alternate = 5 },
  [TIM15_CH1N_PB13] = { .port = GPIOB, .pin = 13, .alternate = 5 },
  [TIM15_CH1_PB14] = { .port = GPIOB, .pin = 14, .alternate = 5 },
  [TIM15_CH1N_PB15] = { .port = GPIOB, .pin = 15, .alternate = 4 },
  [TIM15_CH2_PB15] = { .port = GPIOB, .pin = 15, .alternate = 5 },
  [TIM15_CH1_PC1] = { .port = GPIOC, .pin = 1, .alternate = 2 },
  [TIM15_CH2_PC2] = { .port = GPIOC, .pin = 2, .alternate = 2 },
  [TIM16_CH1_PA6] = { .port = GPIOA, .pin = 6, .alternate = 5 },
  [TIM16_CH1N_PB6] = { .port = GPIOB, .pin = 6, .alternate = 2 },
  [TIM16_CH1_PB8] = { .port = GPIOB, .pin = 8, .alternate = 2 },
  [TIM16_CH1_PD0] = { .port = GPIOD, .pin = 0, .alternate = 2 },
  [TIM17_CH1_PA7] = { .port = GPIOA, .pin = 7, .alternate = 5 },
  [TIM17_CH1N_PB7] = { .port = GPIOB, .pin = 7, .alternate = 2 },
  [TIM17_CH1_PB9] = { .port = GPIOB, .pin = 9, .alternate = 2 },
  [TIM17_CH1_PD1] = { .port = GPIOD, .pin = 1, .alternate = 2 },
  #ifdef STM32G0C1xx
    [TIM14_CH1_PA4] = { .port = GPIOA, .pin = 4, .alternate = 4 },
    [TIM14_CH1_PA7] = { .port = GPIOA, .pin = 7, .alternate = 4 },
    [TIM14_CH1_PB1] = { .port = GPIOB, .pin = 1, .alternate = 0 },
    [TIM14_CH1_PC12] = { .port = GPIOC, .pin = 12, .alternate = 2 },
  #endif
};
